# Generated by Django 5.1.14 on 2025-12-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the person requesting consultation', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this request has been addressed')),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
