# Generated by Django 5.1.14 on 2025-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(blank=True, help_text='Full Name of the person', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='service',
            field=models.CharField(blank=True, help_text='Service interested in', max_length=100, null=True),
        ),
    ]
