# Generated by Django 5.0.14 on 2025-11-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_case_service_remove_service_price_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for Payment'), ('PAID', 'Payment Confirmed / Ready for Staff'), ('IN_PROGRESS', 'Processing by Staff'), ('NEEDS_DOCUMENTS', 'Awaiting Client Documents'), ('COMPLETED', 'Case Filed & Closed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount charged (auto-populated from ServicePlan).', max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique ID from the payment gateway (simulated).', max_length=255, null=True, unique=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.case')),
            ],
        ),
    ]
