# Generated by Django 5.1.14 on 2025-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_case_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=models.TextField(blank=True, default='', help_text='Line-separated list of deliverables'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Line-separated list of features'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='📋', help_text='Emoji icon', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Line-separated list of required documents'),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline',
            field=models.CharField(blank=True, default='3-5 working days', max_length=100),
        ),
    ]
