# Generated by Django 5.1.14 on 2025-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_deliverables_service_features_service_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(default='📂', help_text='Emoji icon', max_length=10),
        ),
    ]
