# Generated by Django 5.1.14 on 2025-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='detail_description',
            field=models.TextField(blank=True, help_text='Long description for the category detail page', null=True),
        ),
    ]
