# Generated by Django 5.1.14 on 2025-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicecategory_detail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_description',
            field=models.TextField(blank=True, help_text='Long description for the service detail page', null=True),
        ),
    ]
